### ISSUE TITLE
CSS值和单位简述

### ISSUE THREAD

**Issue by liangfengbo** [liangfengbo/frontend-ability#3]
## CSS的值

- 数值
- 百分比
- 颜色
- 坐标位置
- 函数

## 数值单位

- 像素 (px) 是一种绝对单位（absolute units）
- em:1em与当前元素的字体大小相同
- rem: REM（root em）和em以同样的方式工作
- vw, vh: 分别是视口宽度的1/100和视口高度的1/100

```css
p {
  margin: 5px;
  padding: 10px;
  border: 2px solid black;
  background-color: cyan;
}
```

## 百分比

- 它们的长度总是保持相同的长度，与它们的父容器的宽度发生变化。

```css
.box {
  width: 100px；
  
  & .item {
    width: 100%;
  }
}
```

## 颜色

- 十六进制值
- RGB
- HSL
- RGBA 和 HSLA
- 不透明度（Opacity）

```css
p {
  background-color: red;
}

p:nth-child(1) {
  background-color: rgb(255,255,255);
}

p:nth-child(2) {
  background-color: hsl(0,100%,50%);
}

p:nth-child(3) {
  background-color: rgba(255,0,0,0.5);
}

p:nth-child(4) {
  background-color: hsla(240,100%,50%,0.5);
}

p:nth-child(5) {
  background-color: rgb(255,0,0);
  opacity: 0.5;
}
```

## 函数

在程序中， functions是代码中的可重复使用的部分，它可以多次运行，以便使开发人员和计算机以最小的代价完成重复的任务。函数通常存在于JavaScript，Python，C++等语言，但它也作为属性值存在于CSS中。我们已经在Colors部分中看到函数了，例如 rgb(), hsl()：

```css
background-color: rgba(255,0,0,0.5);

background-color: hsla(240,100%,50%,0.5);

transform: rotate(45deg);

transform: translate(50px, 60px); 

width: calc(90%-15px);

background-image: url('myimage.png');
```

[MDN:CSS的值和单位](https://developer.mozilla.org/zh-CN/docs/Learn/CSS/Introduction_to_CSS/Values_and_units)

[CSS 单位与属性](https://blog.csdn.net/haoranli/article/details/72831009)
